title: "Nautical Analysis"
description: "Cybersecurity insights with a nautical perspective"
baseurl: "" 
url: "https://nauticalanalysis.github.io"

theme: minima  # Or try "cayman", "hacker", etc.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
